// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: cosmos/mymodule/v1beta1/query.proto

package v1beta1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryHelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *QueryHelloRequest) Reset() {
	*x = QueryHelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmos_mymodule_v1beta1_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryHelloRequest) ProtoMessage() {}

func (x *QueryHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cosmos_mymodule_v1beta1_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryHelloRequest.ProtoReflect.Descriptor instead.
func (*QueryHelloRequest) Descriptor() ([]byte, []int) {
	return file_cosmos_mymodule_v1beta1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type QueryHelloResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *QueryHelloResponse) Reset() {
	*x = QueryHelloResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmos_mymodule_v1beta1_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryHelloResponse) ProtoMessage() {}

func (x *QueryHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cosmos_mymodule_v1beta1_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryHelloResponse.ProtoReflect.Descriptor instead.
func (*QueryHelloResponse) Descriptor() ([]byte, []int) {
	return file_cosmos_mymodule_v1beta1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_cosmos_mymodule_v1beta1_query_proto protoreflect.FileDescriptor

var file_cosmos_mymodule_v1beta1_query_proto_rawDesc = []byte{
	0x0a, 0x23, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x6d, 0x79, 0x6d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x6d, 0x79,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x11,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2e, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x92, 0x01, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12,
	0x88, 0x01, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x2a, 0x2e, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x2e, 0x6d, 0x79, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x62, 0x65,
	0x74, 0x61, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x6d,
	0x79, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x26, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x20, 0x12, 0x1e, 0x2f, 0x63, 0x6f, 0x73,
	0x6d, 0x6f, 0x73, 0x2f, 0x6d, 0x79, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x62,
	0x65, 0x74, 0x61, 0x31, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x42, 0x47, 0x5a, 0x45, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f,
	0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x78, 0x2f, 0x6d, 0x79, 0x6d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x2f, 0x6d, 0x79, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x62, 0x65,
	0x74, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cosmos_mymodule_v1beta1_query_proto_rawDescOnce sync.Once
	file_cosmos_mymodule_v1beta1_query_proto_rawDescData = file_cosmos_mymodule_v1beta1_query_proto_rawDesc
)

func file_cosmos_mymodule_v1beta1_query_proto_rawDescGZIP() []byte {
	file_cosmos_mymodule_v1beta1_query_proto_rawDescOnce.Do(func() {
		file_cosmos_mymodule_v1beta1_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_cosmos_mymodule_v1beta1_query_proto_rawDescData)
	})
	return file_cosmos_mymodule_v1beta1_query_proto_rawDescData
}

var file_cosmos_mymodule_v1beta1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cosmos_mymodule_v1beta1_query_proto_goTypes = []interface{}{
	(*QueryHelloRequest)(nil),  // 0: cosmos.mymodule.v1beta1.QueryHelloRequest
	(*QueryHelloResponse)(nil), // 1: cosmos.mymodule.v1beta1.QueryHelloResponse
}
var file_cosmos_mymodule_v1beta1_query_proto_depIdxs = []int32{
	0, // 0: cosmos.mymodule.v1beta1.Query.Hello:input_type -> cosmos.mymodule.v1beta1.QueryHelloRequest
	1, // 1: cosmos.mymodule.v1beta1.Query.Hello:output_type -> cosmos.mymodule.v1beta1.QueryHelloResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cosmos_mymodule_v1beta1_query_proto_init() }
func file_cosmos_mymodule_v1beta1_query_proto_init() {
	if File_cosmos_mymodule_v1beta1_query_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cosmos_mymodule_v1beta1_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryHelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cosmos_mymodule_v1beta1_query_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryHelloResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cosmos_mymodule_v1beta1_query_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cosmos_mymodule_v1beta1_query_proto_goTypes,
		DependencyIndexes: file_cosmos_mymodule_v1beta1_query_proto_depIdxs,
		MessageInfos:      file_cosmos_mymodule_v1beta1_query_proto_msgTypes,
	}.Build()
	File_cosmos_mymodule_v1beta1_query_proto = out.File
	file_cosmos_mymodule_v1beta1_query_proto_rawDesc = nil
	file_cosmos_mymodule_v1beta1_query_proto_goTypes = nil
	file_cosmos_mymodule_v1beta1_query_proto_depIdxs = nil
}
